### DISCUSSION TITLE
How do we deal with tags within a selector?

### DISCUSSION THREAD

**Discussion by MarkJaroski** [jakopako/croncert-config#152] [Q&A] [answered]
So my next contribution is a club which normally puts the title in a bare h2 with a css selector like this:

```
<h2>The artist</h2>
```

But sometimes they add tags within the h2, like this:

```
<h2><strong>Another Artist</strong></h2>
```

It seems like this should still work but it doesn't. Is there a way to get goskyr to recurse?

The site in question is here: https://www.leboutdumonde.ch/programme/

**Comment by jakopako** [comment, marked as answer]
yeah, I encountered the same issue a while ago so I added a param `entire_subtree` to the location of a field. For your case this should be something like this:
```
      - name: title
        type: text
        location:
          selector: h2
          entire_subtree: true
```
