### DISCUSSION TITLE
I thought I understood entire_subtree, then

### DISCUSSION THREAD

**Discussion by MarkJaroski** [jakopako/croncert-config#161] [Q&A] [answered]
I'm trying to write a config for an itinerant "club" in Lausanne called Association du Salopard (the bastard's club). Strangely entire_subtree is not working as expected.

Their even HTML looks like this:

```
                                        <a class="eventItem eventItem--redHover" href="http://salopard.ch/event/alice-attention-le-tapis-prend-feu-clara-le-meur/">
        <!- other interesting info -->
        <h2 class="eventItem__title">
                <p>ALICE<br />
+ ATTENTION LE TAPIS PREND FEU<br />
+ CLARA LE MEUR</p>

        </h2>
        <!-- other interesting info -->
</a>
```

and here's the config.yml so far:

```
scrapers:
  - name: Salopord
    url: http://salopard.ch/
    item: a.eventItem
    fields:
      - name: city
        value: Lausanne
      - name: title
        location: 
          selector: .eventItem__title p
        entire_subtree: true
        node_index: 0 # attempt to get entire_subtree to work the way I expect it to
        can_be_empty: true
```

and here's the goskyr run:

```
$ ./goskyr 
2023/02/19 16:41:48 scraping Salopord
2023/02/19 16:41:49 fetched 6 Salopord items
{
  "city": "Lausanne",
  "title": "ŠIROM"
}
{
  "city": "Lausanne",
  "title": "ALICE"
}
{
  "city": "Lausanne",
  "title": "EUGENE CHADBOURNE"
}
{
  "city": "Lausanne",
  "title": "DOMI CHANSORN & THE ASTRAL BODY"
}
{
  "city": "Lausanne",
  "title": "METIUS (JACCO GARDNER)"
}
{
  "city": "Lausanne",
  "title": "LOUIS JUCKER & BAND"
}
```

**Comment by MarkJaroski** [comment, marked as answer]
The `entire_subtree` belongs to `location` and must be under it. The config above should be:

```
scrapers:
  - name: Salopord
    url: http://salopard.ch/
    item: a.eventItem
    fields:
      - name: city
        value: Lausanne
      - name: title
        location: 
          selector: .eventItem__title p
          entire_subtree: true
        node_index: 0 # attempt to get entire_subtree to work the way I expect it to
        can_be_empty: true
```
