### DISCUSSION TITLE
More festival

### DISCUSSION THREAD

**Discussion by MarkJaroski** [jakopako/croncert-config#175] [General]
Urban festivals often rely on local bars and small venues to host their concerts. This is a good way for locals to discover smaller venues, and the same goes for projects like this one. We can learn a lot from festivals.

But sometimes these things present their own challenges. For instance just now I've been working on the Premises festival, which concentrates on local artists:

https://www.premices.ch/programme

Looks pretty straight-forward, right? But no. There's no reference to the date anywhere, just "vendredi" and "samedi". The assumption is that human users of the site will convert "vendredi" in their heads to something like "2023-03-17", and we do! But right now there's no regex-replace in goskyr, so it can't do that.

I thought about trying to make two configs with the date as a fixed value. That doesn't work either.

Would you be interested in a code submission to try to address this? If so what do you think is the best approach?

**Comment by jakopako** [comment]
Very good input! Thanks so much!

So there are a couple of good ideas here. The first one is that it should be possible to have fixed values for a field of type 'date'. I'll make an issue for this.

Regarding the regex replace functionality. Maybe, config-wise, we can do something like this:
```
- name: field-with-repl
  location:
    selector: p.some-class
  transform:
    - type: regex-replace
      regex: some-regex
      replace: some-string
```
Maybe later there'll be other transformations (or maybe there is a better term for this?) as well, eg to-lower (to-lower would only need type and not the other two params). The transform param should also be available for date components. So I guess in your example you'd have something like:
```
- name: date
  type: date
  components:
    - covers: 
        day: true
        month: true
        year: true
      location:
        selector: some-selector
      transform:
        - type: regex-replace
          regex: Vendredi
          replace: 17-3-2023
        - type: regex-replace
          regex: Samedi
          replace: 18-3-2023
      layout: ["2-1-2006"]
```

I think this would be how I'd attempt to tackle this. What do you think, does this make sense? And yes, I'd be happy to receive a code submission that tackles this :)
