### DISCUSSION TITLE
How does the ID selector work "#some_id"

### DISCUSSION THREAD

**Discussion by MarkJaroski** [jakopako/croncert-config#184] [Q&A] [answered]
It seems that for some reason the ID selector in CSS and GoQuery doesn't work. 

I don't know if this is because I'm using it wrong, or if there's some other GoQuery quirk that I'm unaware of.

Guidance would be appreciated.

FWIW, this is what I'm trying to do:
```

  - name: CafeOto
    url: https://www.cafeoto.co.uk/events/
    item: body.event-overview > div.content-push > div.activity-container.events.clearfix > div.container-fluid > div.row > div.activity-container-inner > div.each-activity.col-xs-12.col-sm-5.col-sm-offset-rt-1
    paginator:
      location:
        selector: "div#iscroll_other"
        attr: href
 
```
