### ISSUE TITLE
Support times with only the hour part

### ISSUE THREAD

**Issue by MarkJaroski** [jakopako/croncert-config#147]
Maybe there's already a way to do this with regex, but so far at least I haven't found it in the main config. 

One of the venues I'm working on lists time on the hour without the minute part. They do it French style, so it should be 21h00, but they just use 21h. To be clear if it's at 21:30 they will write 21h30, but for a concert at 21:00 they just write 21h.

Is this already possible somehow?

**Comment by MarkJaroski** [comment]
For more clarity, here is the particular example I'm working with:

```
scrapers:
  - name: Le Bout du Monde
    url: https://www.leboutdumonde.ch/programme/
    item: body.page-template-page-no-title.page-template-page-no-title-php.wp-custom-logo.programme > div.site > main.site-main > article.post-2.page.type-page.status-publish.has-post-thumbnail.hentry > section.list_program > ul.events > li.event.has_thumb
    fields:
      - name: date
        type: date
        components:
          - covers:
              day: true
              month: true
            location:
              selector: div.event_header > time
              regex_extract:
                exp: "[0-9]{2}.[0-9]{2}"
            layout: ["02.01"]
          - covers:
              time: true
            location:
              selector: div.event_header > span.hours
              regex_extract:
                exp: "[0-9]{2}h[0-9]?[0-9]?"
            layout: ["15h04"]
        date_location: "Europe/Berlin"
        date_language: fr_FR
      - name: type
        type: text
        location:
          selector: div.event_header > span.style
      - name: title
        type: text
        location:
          selector: h2
      - name: comment
        type: text
        location:
          selector: p > a.notInline
      - name: url
        type: url
        location:
          selector: a.more
          attr: href
    renderJs: true
```

With these errors:

```
2023/02/15 20:07:17 Le Bout du Monde ERROR: error while parsing field date: parsing time "16.02 21h 2023 " as "02.01 15h04 2006 ": cannot parse " 2023 " as "04". Skipping item map[].
2023/02/15 20:07:17 Le Bout du Monde ERROR: error while parsing field title: field title cannot be empty. Skipping item map[date:2023-02-23 20:30:00 +0100 CET type:Jam].
2023/02/15 20:07:17 Le Bout du Monde ERROR: error while parsing field date: parsing time "26.02 17h 2023 " as "02.01 15h04 2006 ": cannot parse " 
```
