### ISSUE TITLE
Add Brick

### ISSUE THREAD

**Issue by jakopako** [jakopako/croncert-config#165]
http://brickbar.ch/ueber-mich/

Zurich

**Comment by jakopako** [comment]
Currently, with goskyr v0.3.3 not possible to scrape. The issue seems to be that we need text from the list of items that has the same selector as the item itself. So a config would possibly look something like this: 
```
scrapers:
  - name: http://brickbar.ch/ueber-mich/
    url: http://brickbar.ch/ueber-mich/
    item: div.entry-content > p
    fields:
      - name: field-0
        type: text
      - name: field-1
        type: text
        location:
          child_index: 2
```

But the empty selector for the fields currently does not result in the desired output.
