### ISSUE TITLE
Add Dachstock

### ISSUE THREAD

**Issue by laerm** [jakopako/croncert-config#187]
I have a semi working configuration for Dachstock in Bern:

```yml
  - name: Dachstock
    url: https://www.dachstock.ch/events
    item: div.event-teaser-info
    fields:
      - name: "location"
        value: "Dachstock"
      - name: "city"
        value: "Bern"
      - name: "type"
        value: "concert"
      - name: "sourceUrl"
        value: https://www.dachstock.ch/events
      - name: "date"
        type: "date"
        components:
          - covers:
              day: true
              month: true
              year: true
              time: true
            location:
              selector: a.event-date
              regex_extract:
                exp: "[0-9]{2}.[0-9]{2}.[0-9]{4} - [0-9]{2}:[0-9]{2}"
            layout: ["02.01.2006 - 15:04"]
        date_location: "Europe/Berlin"
        date_language: "de_DE"
      - name: "url"
        type: url
        location:
          selector: div.event-teaser-top > a
          attr: href
      - name: "title"
        type: text
        location:
          selector: div.artist-name
      - name: "comment"
        type: text
        location:
          selector: div.event-title
        can_be_empty: true
```

Only issue is, when there's a number of artists on the same night, it'll only return the first occurrence of div.artist-name. Any ideas how I could aggregate all div.artist-name? Or a better way of dealing with this?

**Comment by MarkJaroski** [comment]
Shuba's Tavern in Chicago has the same issue FWIW.

**Comment by laerm** [comment]
Same for Fri-Son in Fribourg after a overly quick look at the website's html.

**Comment by MarkJaroski** [comment]
Off-topic: @laerm, Are you working on Fribourg? It would be good also to have the Spirale and Ancienne Gare at least.

**Comment by laerm** [comment]
Hey @MarkJaroski I don't know those venues. Will take a look when I have a moment, unless you're itching to get to work on them.

**Comment by MarkJaroski** [comment]
Either way. I'm happy to work on them, or you can if you prefer. Here are the venues I know about in or near Fribourg:

https://laspirale.ch/

https://nouveaumonde.ch/

https://club.badbonn.ch/

**Comment by laerm** [comment]
Bad Bonn was added a few days back. Reminder if anyone's interested in arguably the best festival in Switzerland, Bad Bonn Kilbi! Lineup and tickets go on sale next week: https://kilbi.badbonn.ch/ Be quick, they tend to sell out within minutes!

**Comment by MarkJaroski** [comment]
Check out their partners list from last year:

https://kilbi.badbonn.ch/2022/en/partners

And compare that with the list of clubs I've already added. It's pretty weird and cool to see Café Oto turn up in the list.

**Comment by laerm** [comment]
I'd never heard of Café Oto, seems very cool. Need to add it to my list next time I'm in London.

**Comment by MarkJaroski** [comment]
I had a conversation with Mark Lockheart after a _Polar Bear_ concert in Lausanne and asked him if there was an equivalent to Bimhaus (Amsterdam) or the Empty Bottle (Chicago) in London. He suggested Café Oto. I've been there a bunch of times since. It's really cool, and so is the neighbourhood.

**Comment by MarkJaroski** [comment]
Empty bottle is an outlier since they mostly book indie rock, but they have a reserved Wednesday night series for oddball Jazz going back to the mid-nineties, around the time that the Art Ensemble of Chicago repatriated from their 25-year residency in Paris.

It was a cool time to be in Chicago. It was almost worth dealing with winter.

**Comment by jakopako** [comment]
The issue should be solved now with the latest version 0.4.3. For the title field of Dachstock you can try
```
      - name: "title"
        type: text
        location:
          selector: div.artist-name
          all_nodes: true
          separator: ", "
```

There is also a second mechanism of joining various strings, see goskyr's README, https://github.com/jakopako/goskyr#dynamic-fields depending on the use case. Let me know if you have any issues.
