### ISSUE TITLE
Add Caves du Manoir at Martigny

### ISSUE THREAD

**Issue by oinska** [jakopako/croncert-config#329]
```
fields:
  - name: "type"
    value: "concert"
  - name: "city"
    value: "Martigny"
  - name: country
    value: Switzerland
  - name: "location"
    value: "Caves du Manoir"
  - name: "sourceUrl"
    value: "https://cavesdumanoir.ch/"
```
