### ISSUE TITLE
Add Pont Rouge at Monthey

### ISSUE THREAD

**Issue by oinska** [jakopako/croncert-config#330]
```
fields:
  - name: "type"
    value: "concert"
  - name: "city"
    value: "Monthey"
  - name: country
    value: Switzerland
  - name: "location"
    value: "Pont Rouge"
  - name: "sourceUrl"
    value: "https://www.pontrouge.ch/"
```
