### ISSUE TITLE
Add Ebullition au Bulle

### ISSUE THREAD

**Issue by oinska** [jakopako/croncert-config#331]
```
 fields:
  - name: "type"
    value: "concert"
  - name: "city"
    value: "Bulle"
  - name: country
    value: Switzerland
  - name: "location"
    value: "Ebullition"
  - name: "sourceUrl"
    value: "https://ebull.ch/fr"
```
