### ISSUE TITLE
Add Sunset Bar at Martigny

### ISSUE THREAD

**Issue by oinska** [jakopako/croncert-config#332]
```
 fields:
  - name: "type"
    value: "concert"
  - name: "city"
    value: "Martigny"
  - name: country
    value: Switzerland
  - name: "location"
    value: "Sunset Bar"
  - name: "sourceUrl"
    value: "https://www.sunsetbar.info/lieu/sunset-bar/"
```
