### ISSUE TITLE
Add L’Amalgame at Yverdon-les-Bains

### ISSUE THREAD

**Issue by oinska** [jakopako/croncert-config#333]
```
 fields:
  - name: "type"
    value: "concert"
  - name: "city"
    value: "Yverdon-les-Bains"
  - name: country
    value: Switzerland
  - name: "location"
    value: "L’Amalgame"
  - name: "sourceUrl"
    value: "https://www.amalgameclub.ch/programme/"
```
