### ISSUE TITLE
Add Le Port Franc at Sion

### ISSUE THREAD

**Issue by oinska** [jakopako/croncert-config#334]
```
 fields:
  - name: "type"
    value: "concert"
  - name: "city"
    value: "Sion"
  - name: country
    value: Switzerland
  - name: "location"
    value: "Le Port Franc"
  - name: "sourceUrl"
    value: "https://www.leportfranc.ch/concerts"
```
