### ISSUE TITLE
Add Point11 at Sion

### ISSUE THREAD

**Issue by oinska** [jakopako/croncert-config#336]
```
 fields:
  - name: "type"
    value: "concert"
  - name: "city"
    value: "Sion"
  - name: country
    value: Switzerland
  - name: "location"
    value: "Point11"
  - name: "sourceUrl"
    value: "http://point11.ch/site/home"
```
