### ISSUE TITLE
Add NED Music Club at Montreux

### ISSUE THREAD

**Issue by oinska** [jakopako/croncert-config#337]
```
 fields:
  - name: "type"
    value: "concert"
  - name: "city"
    value: "Montreux"
  - name: country
    value: Switzerland
  - name: "location"
    value: "NED Music Club"
  - name: "sourceUrl"
    value: "https://www.ned.ch/"
```
