### ISSUE TITLE
Add Manoir Pub at Saint-Maurice

### ISSUE THREAD

**Issue by oinska** [jakopako/croncert-config#338]
This bar seems quiet at the moment, but sometimes there are fabulous concerts!
This is a Google Calendar with plant closures... I don't know if it works.

```
 fields:
  - name: "type"
    value: "concert"
  - name: "city"
    value: "Saint-Maurice"
  - name: country
    value: Switzerland
  - name: "location"
    value: "Manoir Pub"
  - name: "sourceUrl"
    value: "https://manoirpub.ch/evenements/"
```
